version: '3'

services:
  minecraft:
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "vol-minecraft:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 12G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      LEVEL_TYPE: DEFAULT
      MAX_PLAYERS: 20
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
    image: itzg/minecraft-server
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  vol-minecraft:
  rcon:
